// MatchHala - أسئلة إضافية للألعاب (تُلحق بنهاية البنوك في gameQuestions.js)
// نفس القواعد: مستوى خفيف، لا جنس، لا طلب صورة شخصية أو بيانات اتصال.
// ⚠️ لا تُعِد ترتيب العناصر — أضف في النهاية فقط (utils/gameBanks.js يعتمد على العدد المزروع).

const TRUTHS = [
    { ar: 'ما أول شيء تفعله حين تستيقظ؟', en: 'What is the first thing you do when you wake up?' },
    { ar: 'ما الشيء الذي يجعلك تشعر بالأمان؟', en: 'What makes you feel safe?' },
    { ar: 'ما أجمل مكان زرته في حياتك؟', en: 'What is the most beautiful place you have visited?' },
    { ar: 'من الشخص الذي تتصل به أولاً عند سماع خبر سعيد؟', en: 'Who do you call first with good news?' },
    { ar: 'ما العادة التي تتمنى التخلص منها؟', en: 'Which habit do you wish you could drop?' },
    { ar: 'ما أكثر شيء يرفع معنوياتك عندما تكون حزيناً؟', en: 'What lifts your mood when you feel down?' },
    { ar: 'ما الموهبة التي تتمنى أن تمتلكها؟', en: 'Which talent do you wish you had?' },
    { ar: 'ما أطول وقت قضيته دون هاتف؟', en: 'What is the longest you have gone without your phone?' },
    { ar: 'ما الوجبة التي لا تملّ منها أبداً؟', en: 'Which meal do you never get tired of?' },
    { ar: 'ما أول شيء تشتريه لو ربحت مبلغاً كبيراً؟', en: 'What is the first thing you would buy if you won a fortune?' },
    { ar: 'ما الشيء الذي تفتخر أن أهلك علّموك إياه؟', en: 'What are you proud your family taught you?' },
    { ar: 'ما أسوأ عمل قمت به؟', en: 'What is the worst job you have had?' },
    { ar: 'ما الصفة التي يمدحك الناس عليها دائماً؟', en: 'What trait do people always praise you for?' },
    { ar: 'هل تفضّل أن تُفاجَأ أم أن تعرف مسبقاً؟ ولماذا؟', en: 'Do you prefer surprises or knowing ahead? Why?' },
    { ar: 'ما اللحظة التي تتمنى لو صوّرتها ولم تفعل؟', en: 'Which moment do you wish you had captured but did not?' },
    { ar: 'ما الكتاب أو الفيلم الذي غيّر نظرتك للحياة؟', en: 'Which book or film changed how you see life?' },
    { ar: 'ما الشيء الذي تفعله لتهدأ عندما تتوتر؟', en: 'What do you do to calm down when stressed?' },
    { ar: 'ما أغرب حلم رأيته؟', en: 'What is the strangest dream you have had?' },
    { ar: 'ما الكلمة التي تكررها كثيراً دون أن تنتبه؟', en: 'Which word do you repeat without noticing?' },
    { ar: 'ما اليوم الذي تعتبره الأسعد في حياتك حتى الآن؟', en: 'Which day is the happiest of your life so far?' },
    { ar: 'ما الشيء الذي تتمنى أن تتعلمه هذا العام؟', en: 'What do you wish to learn this year?' },
    { ar: 'ما أكثر شيء تفتقده من طفولتك؟', en: 'What do you miss most about your childhood?' },
    { ar: 'لو كتبت رسالة لنفسك قبل عشر سنوات، ماذا تقول فيها؟', en: 'What would you tell yourself ten years ago?' },
    { ar: 'ما الشيء الصغير الذي يزعجك جداً في الآخرين؟', en: 'What small thing annoys you about others?' },
    { ar: 'ما أكثر مكان تشعر فيه بالراحة؟', en: 'Where do you feel most at ease?' },
    { ar: 'ما القرار الجريء الذي أخذته ولم تندم عليه؟', en: 'What bold decision did you make and never regret?' },
    { ar: 'ما الأغنية التي تذكّرك بأجمل مرحلة في حياتك؟', en: 'Which song reminds you of the best period of your life?' },
    { ar: 'ما الشيء الذي تحب أن يفعله لك أصدقاؤك ولا تطلبه؟', en: 'What do you wish friends would do for you without asking?' },
    { ar: 'ما أكثر شيء يضحكك في الأفلام الكوميدية؟', en: 'What makes you laugh most in comedies?' },
    { ar: 'لو كنت شخصية كرتونية، من تكون ولماذا؟', en: 'If you were a cartoon character, who and why?' },
    { ar: 'ما أول تطبيق تفتحه كل صباح؟', en: 'What is the first app you open each morning?' },
    { ar: 'ما الهواية التي بدأتها ثم تركتها؟', en: 'Which hobby did you start and quit?' },
    { ar: 'ما أكثر شيء تحسدك عليه نفسك القديمة؟', en: 'What would your younger self envy about you?' },
    { ar: 'هل تعتبر نفسك شخصاً صبوراً؟ احكِ موقفاً يثبت ذلك.', en: 'Are you patient? Share a moment that proves it.' },
    { ar: 'ما الشيء الذي تتمنى أن يتغيّر في العالم؟', en: 'What do you wish would change in the world?' },
    { ar: 'ما أكثر شيء تخشى أن تخسره؟', en: 'What are you most afraid of losing?' },
    { ar: 'ما اللقب الذي تتمنى أن يناديك الناس به؟', en: 'What nickname do you wish people used for you?' },
    { ar: 'ما أول انطباع تركته عند شخص ثم اكتشفت أنه خاطئ؟', en: 'What first impression of you turned out wrong?' },
    { ar: 'ما الشيء الذي تقوله لنفسك كلما تعبت؟', en: 'What do you tell yourself when you are tired?' },
    { ar: 'ما أجمل رسالة وصلتك في حياتك؟', en: 'What is the nicest message you have ever received?' },
    { ar: 'ما المكان الذي حلمت بزيارته منذ الصغر؟', en: 'What place have you dreamed of visiting since childhood?' },
    { ar: 'ما الشيء الذي تعتبره أهم صفة في الصداقة؟', en: 'What is the most important quality in friendship?' },
    { ar: 'ما الأمر الذي كنت تظنه صعباً ثم اكتشفت أنه سهل؟', en: 'What seemed hard but turned out easy?' },
    { ar: 'ما أكثر عبارة تحب سماعها؟', en: 'What phrase do you love hearing most?' },
    { ar: 'ما الشيء الذي يجعلك تنسى الوقت؟', en: 'What makes you lose track of time?' },
    { ar: 'لو استطعت تناول العشاء مع أي شخص في التاريخ، من يكون؟', en: 'Who in history would you have dinner with?' }
];

const DARES = [
    { ar: 'أرسل رسالة صوتية تقلّد فيها مذيعاً رياضياً يعلّق على يومك.', en: 'Send a voice message as a sports commentator narrating your day.' },
    { ar: 'اكتب قصيدة قصيرة من بيتين عن القهوة أو الشاي.', en: 'Write a two-line poem about coffee or tea.' },
    { ar: 'أرسل صورة لأقدم شيء تملكه.', en: 'Send a photo of the oldest thing you own.' },
    { ar: 'سجّل رسالة صوتية تعدّ فيها من ١٠ إلى ١ بأسلوب إطلاق صاروخ.', en: 'Count down from 10 to 1 like a rocket launch in a voice message.' },
    { ar: 'صف طعم آخر وجبة أكلتها كأنك ناقد مطاعم محترف.', en: 'Describe your last meal like a professional food critic.' },
    { ar: 'أرسل صورة لمنظر النافذة عندك الآن.', en: 'Send a photo of the view from your window right now.' },
    { ar: 'اخترع مثلاً شعبياً جديداً واشرح معناه.', en: 'Invent a new proverb and explain what it means.' },
    { ar: 'سجّل رسالة صوتية تهمس فيها بسرٍّ صغير عن يومك.', en: 'Whisper a tiny secret about your day in a voice message.' },
    { ar: 'اكتب ثلاث أمنيات لعام قادم في سطر واحد.', en: 'Write three wishes for next year in one line.' },
    { ar: 'أرسل صورة لأغرب شيء في مطبخك.', en: 'Send a photo of the strangest thing in your kitchen.' },
    { ar: 'مثّل بصوتك مشهد مطعم: زبون غاضب ونادل هادئ، في رسالة صوتية.', en: 'Act out an angry customer and calm waiter in a voice message.' },
    { ar: 'أرسل اقتباساً تحبه وقل لماذا يعني لك.', en: 'Send a quote you like and say why it matters to you.' },
    { ar: 'سمِّ فيلماً تستخدم مشاهده لوصف أسبوعك.', en: 'Name a movie that describes your week.' },
    { ar: 'أرسل صورة لكتاب أو مسلسل تنصح به.', en: 'Send a photo of a book or a show you recommend.' },
    { ar: 'قلّد صوت شخصية كرتونية تحبها في رسالة صوتية.', en: 'Imitate a cartoon character in a voice message.' },
    { ar: 'اكتب رسالة شكر قصيرة لأحد أفراد أسرتك (دون ذكر اسمه).', en: 'Write a short thank-you note to a family member (no names).' },
    { ar: 'صوّر ظلّك أو ظلّ شيء بجانبك بشكل فني.', en: 'Take an artistic photo of your shadow or an object\'s shadow.' },
    { ar: 'غنِّ «عيد ميلاد سعيد» بأسلوب أوبرا في رسالة صوتية.', en: 'Sing "Happy Birthday" opera-style in a voice message.' },
    { ar: 'أرسل صورة لأجمل لون تراه حولك الآن.', en: 'Send a photo of the nicest color around you right now.' },
    { ar: 'صف يومك المثالي في ثلاث جمل.', en: 'Describe your perfect day in three sentences.' },
    { ar: 'أرسل صورة لأقرب نبتة أو شجرة إليك.', en: 'Send a photo of the nearest plant or tree.' },
    { ar: 'اكتب عنواناً لفيلم حياتك وملخصاً من سطر.', en: 'Write a title and one-line summary for the movie of your life.' },
    { ar: 'أرسل رسالة صوتية بها أطرف ضحكة عندك.', en: 'Send a voice message with your funniest laugh.' },
    { ar: 'اقترح لنا نشاطاً ممتعاً نجرّبه معاً لو التقينا.', en: 'Suggest a fun activity we could try if we met.' },
    { ar: 'صف شعورك الآن بلون وطعم وصوت.', en: 'Describe how you feel now as a color, a taste and a sound.' },
    { ar: 'سجّل رسالة صوتية تقرأ فيها قائمة مشتريات كأنها خطاب مهم.', en: 'Read a shopping list like an important speech in a voice message.' },
    { ar: 'أرسل صورة لمكان تحب الجلوس فيه.', en: 'Send a photo of a place you love to sit.' },
    { ar: 'ارسم وجهاً مبتسماً بأغرب طريقة وصوّره.', en: 'Draw a smiley in the weirdest way and photograph it.' },
    { ar: 'أخبرنا بمعلومة غريبة تعرفها لا يعرفها الكثيرون.', en: 'Tell us an odd fact few people know.' },
    { ar: 'اكتب مطلع رواية من جملتين عن لقاء غير متوقع.', en: 'Write a two-sentence novel opening about an unexpected meeting.' }
];

const WOULD_YOU_RATHER = [
    { a: { ar: 'أن تسافر كل عام لبلد جديد', en: 'Travel to a new country every year' }, b: { ar: 'أن تعيش في بلد واحد تحبه', en: 'Live in one country you love' } },
    { a: { ar: 'صديق واحد مقرّب', en: 'One very close friend' }, b: { ar: 'عشرة أصدقاء عاديين', en: 'Ten casual friends' } },
    { a: { ar: 'أن تكون الأذكى في الغرفة', en: 'Be the smartest in the room' }, b: { ar: 'أن تكون الأطرف في الغرفة', en: 'Be the funniest in the room' } },
    { a: { ar: 'إجازة في جزيرة هادئة', en: 'A vacation on a quiet island' }, b: { ar: 'إجازة في مدينة مليئة بالأحداث', en: 'A vacation in a lively city' } },
    { a: { ar: 'أن تتذكر كل شيء', en: 'Remember everything' }, b: { ar: 'أن تنسى ما يزعجك فقط', en: 'Forget only what bothers you' } },
    { a: { ar: 'بيت كبير بعيد عن الناس', en: 'A big house far from people' }, b: { ar: 'شقة صغيرة في قلب المدينة', en: 'A small flat in the city center' } },
    { a: { ar: 'أن تكتب كتاباً ينجح', en: 'Write a hit book' }, b: { ar: 'أن تغني أغنية تشتهر', en: 'Sing a famous song' } },
    { a: { ar: 'أن تطبخ لعشرة ضيوف', en: 'Cook for ten guests' }, b: { ar: 'أن تُدعى لعشاء عشرة أشخاص', en: 'Be invited to a ten-person dinner' } },
    { a: { ar: 'أن تعرف الحقيقة دائماً', en: 'Always know the truth' }, b: { ar: 'أن يصدّقك الجميع دائماً', en: 'Always be believed' } },
    { a: { ar: 'فطور كبير كل يوم', en: 'A big breakfast every day' }, b: { ar: 'عشاء كبير كل يوم', en: 'A big dinner every day' } },
    { a: { ar: 'أن تعيش في الماضي بلا تقنية', en: 'Live in the past without technology' }, b: { ar: 'أن تعيش في المستقبل بتقنية مذهلة', en: 'Live in a future with amazing tech' } },
    { a: { ar: 'مقابلة شخصيتك المفضلة', en: 'Meet your favorite celebrity' }, b: { ar: 'مقابلة أكثر شخص تحترمه', en: 'Meet the person you respect most' } },
    { a: { ar: 'أن تتحدث مع الحيوانات', en: 'Talk to animals' }, b: { ar: 'أن تفهم كل لغات البشر', en: 'Understand every human language' } },
    { a: { ar: 'يوم ممطر مع كتاب', en: 'A rainy day with a book' }, b: { ar: 'يوم مشمس في الحديقة', en: 'A sunny day in the park' } },
    { a: { ar: 'أن تكون دائماً في الموعد بدقة', en: 'Always be exactly on time' }, b: { ar: 'أن تتأخر لكن تصل بحماس', en: 'Be late but arrive full of energy' } },
    { a: { ar: 'مشاهدة مباراة في الملعب', en: 'Watch a match in the stadium' }, b: { ar: 'مشاهدتها في البيت مع الأصدقاء', en: 'Watch it at home with friends' } },
    { a: { ar: 'أن تعمل من البيت', en: 'Work from home' }, b: { ar: 'أن تعمل في مكتب مع زملاء', en: 'Work in an office with colleagues' } },
    { a: { ar: 'أن تعيش بلا موسيقى', en: 'Live without music' }, b: { ar: 'أن تعيش بلا أفلام', en: 'Live without movies' } },
    { a: { ar: 'أن تنام ٥ ساعات وتنجز الكثير', en: 'Sleep 5 hours and get a lot done' }, b: { ar: 'أن تنام ١٠ ساعات وتنجز أقل', en: 'Sleep 10 hours and do less' } },
    { a: { ar: 'أن تُعجَب بك الجماهير', en: 'Be admired by crowds' }, b: { ar: 'أن يحبك القليلون بصدق', en: 'Be truly loved by a few' } },
    { a: { ar: 'سيارة فاخرة قديمة', en: 'An old luxury car' }, b: { ar: 'سيارة عادية حديثة', en: 'A modern ordinary car' } },
    { a: { ar: 'أن تسمع أفكار من تحب', en: 'Hear the thoughts of people you love' }, b: { ar: 'أن يسمع من تحب أفكارك', en: 'Have loved ones hear your thoughts' } },
    { a: { ar: 'تعلّم العزف على البيانو', en: 'Learn to play the piano' }, b: { ar: 'تعلّم الرسم بالزيت', en: 'Learn oil painting' } },
    { a: { ar: 'خروجة عفوية آخر الليل', en: 'A spontaneous late-night outing' }, b: { ar: 'سهرة هادئة في البيت', en: 'A quiet night at home' } },
    { a: { ar: 'أن تعيش في مكان صيفاً دائماً', en: 'Live where it is always summer' }, b: { ar: 'أن تعيش في مكان شتاءً دائماً', en: 'Live where it is always winter' } },
    { a: { ar: 'أن تحصل على ترقية كبيرة', en: 'Get a big promotion' }, b: { ar: 'أن تحصل على إجازة شهر كامل', en: 'Get a full month off' } },
    { a: { ar: 'أن تسافر بالقطار', en: 'Travel by train' }, b: { ar: 'أن تسافر بالطائرة', en: 'Travel by plane' } },
    { a: { ar: 'أن تعيش تجربة الغوص في البحر', en: 'Go scuba diving' }, b: { ar: 'أن تعيش تجربة القفز بالمظلة', en: 'Go skydiving' } },
    { a: { ar: 'المفاجآت السارة القصيرة', en: 'Short pleasant surprises' }, b: { ar: 'انتظار شيء جميل طويلاً', en: 'Long anticipation of something great' } },
    { a: { ar: 'أن تتقن لغة جديدة تماماً', en: 'Master a new language' }, b: { ar: 'أن تتقن رياضة جديدة تماماً', en: 'Master a new sport' } },
    { a: { ar: 'أن تعيش بجانب البحر', en: 'Live by the sea' }, b: { ar: 'أن تعيش بجانب الغابة', en: 'Live by the forest' } },
    { a: { ar: 'مطعم مشهور مزدحم', en: 'A famous crowded restaurant' }, b: { ar: 'مطعم صغير مجهول لذيذ', en: 'A tiny unknown delicious spot' } },
    { a: { ar: 'أن يكون عندك ذاكرة خارقة', en: 'Have a superb memory' }, b: { ar: 'أن يكون عندك حدس خارق', en: 'Have superb intuition' } },
    { a: { ar: 'أن تبدأ مشروعك الخاص', en: 'Start your own business' }, b: { ar: 'أن تعمل في شركة مستقرة', en: 'Work in a stable company' } },
    { a: { ar: 'أن تعيش لحظة جميلة وتنساها', en: 'Live a wonderful moment and forget it' }, b: { ar: 'أن تتذكر لحظة عادية للأبد', en: 'Remember an ordinary moment forever' } },
    { a: { ar: 'رسالة مكتوبة بخط اليد', en: 'A handwritten letter' }, b: { ar: 'مكالمة طويلة', en: 'A long phone call' } },
    { a: { ar: 'المشي في الصباح الباكر', en: 'An early morning walk' }, b: { ar: 'المشي عند الغروب', en: 'A sunset walk' } },
    { a: { ar: 'أن تكون بطل قصة مغامرات', en: 'Be the hero of an adventure story' }, b: { ar: 'أن تكون بطل قصة رومانسية', en: 'Be the hero of a romance' } },
    { a: { ar: 'أن تكون أخاً أكبر/أختاً كبرى', en: 'Be the eldest sibling' }, b: { ar: 'أن تكون الأصغر في العائلة', en: 'Be the youngest sibling' } },
    { a: { ar: 'وجبة سريعة لذيذة', en: 'A tasty fast meal' }, b: { ar: 'وجبة صحية بسيطة', en: 'A simple healthy meal' } },
    { a: { ar: 'أن تعرف مستقبلك', en: 'Know your future' }, b: { ar: 'أن تعيش كل يوم دون معرفة', en: 'Live each day not knowing' } },
    { a: { ar: 'أن تعيش في قصة خيالية', en: 'Live inside a fairy tale' }, b: { ar: 'أن تعيش في رواية بوليسية', en: 'Live inside a detective novel' } },
    { a: { ar: 'يوم كامل من الضحك', en: 'A whole day of laughing' }, b: { ar: 'يوم كامل من الهدوء التام', en: 'A whole day of perfect calm' } },
    { a: { ar: 'أن تُقدَّر أعمالك بعد وفاتك', en: 'Be appreciated after you are gone' }, b: { ar: 'أن تُقدَّر في حياتك بهدوء', en: 'Be quietly appreciated in your lifetime' } }
];

const NEVER_HAVE_I_EVER = [
    { ar: 'لم أقفز في البحر من مكان مرتفع قط', en: 'I have never jumped into the sea from a height' },
    { ar: 'لم أنم في المطار قط', en: 'I have never slept at an airport' },
    { ar: 'لم أفقد حقيبتي أثناء السفر قط', en: 'I have never lost my luggage while traveling' },
    { ar: 'لم أشاهد فيلماً مرتين في السينما قط', en: 'I have never watched a movie twice at the cinema' },
    { ar: 'لم أتعلم عزف آلة موسيقية قط', en: 'I have never learned a musical instrument' },
    { ar: 'لم أجرّب رياضة غريبة قط', en: 'I have never tried an unusual sport' },
    { ar: 'لم أكتب مذكرات قط', en: 'I have never kept a diary' },
    { ar: 'لم أشارك في مسابقة قط', en: 'I have never entered a competition' },
    { ar: 'لم أقف على خشبة مسرح قط', en: 'I have never stood on a stage' },
    { ar: 'لم أزرع نبتة قط', en: 'I have never grown a plant' },
    { ar: 'لم أنسَ اسم شخص أعرفه جيداً قط', en: 'I have never forgotten the name of someone I know well' },
    { ar: 'لم أتأخر عن رحلة طيران قط', en: 'I have never missed a flight' },
    { ar: 'لم أتعلق بمسلسل حتى الفجر قط', en: 'I have never stayed up till dawn for a series' },
    { ar: 'لم أضحك على نكتة لم أفهمها قط', en: 'I have never laughed at a joke I did not get' },
    { ar: 'لم أدخل غرفة ونسيت لماذا دخلتها قط', en: 'I have never walked into a room and forgotten why' },
    { ar: 'لم أخترع اسماً مستعاراً قط', en: 'I have never invented a nickname for myself' },
    { ar: 'لم أشاهد عرض نجوم في الصحراء قط', en: 'I have never stargazed in the desert' },
    { ar: 'لم أركب حصاناً أو جملاً قط', en: 'I have never ridden a horse or a camel' },
    { ar: 'لم أتسلق جبلاً قط', en: 'I have never climbed a mountain' },
    { ar: 'لم أشتر شيئاً لمجرد أن شكله أعجبني قط', en: 'I have never bought something just for how it looks' },
    { ar: 'لم أفتح هديتي قبل موعدها قط', en: 'I have never opened a gift early' },
    { ar: 'لم أصادق شخصاً من بلد آخر قط', en: 'I have never befriended someone from another country' },
    { ar: 'لم أقرأ الرواية بعد مشاهدة فيلمها قط', en: 'I have never read a novel after watching its film' },
    { ar: 'لم أقضِ يوماً كاملاً في السرير قط', en: 'I have never spent a whole day in bed' },
    { ar: 'لم أطبخ وجبة كاملة وحدي قط', en: 'I have never cooked a full meal by myself' },
    { ar: 'لم أشارك في عمل تطوعي قط', en: 'I have never volunteered' },
    { ar: 'لم أتحدث أمام جمع كبير قط', en: 'I have never spoken in front of a large crowd' },
    { ar: 'لم أضع منبهاً ولم أسمعه قط', en: 'I have never set an alarm and slept through it' },
    { ar: 'لم أرقص في حفلة قط', en: 'I have never danced at a party' },
    { ar: 'لم أشاهد مباراة كاملة قط', en: 'I have never watched a full match' },
    { ar: 'لم أغيّر تسريحة شعري بالكامل قط', en: 'I have never completely changed my hairstyle' },
    { ar: 'لم أحتفظ بتذكرة من مكان أحببته قط', en: 'I have never kept a ticket from a place I loved' },
    { ar: 'لم أتعلم كلمات بلغة لا أعرفها قط', en: 'I have never learned words in a language I do not speak' },
    { ar: 'لم أجرب طعاماً غريباً بدافع الفضول قط', en: 'I have never tried an odd food out of curiosity' },
    { ar: 'لم أسمع أغنية أكثر من عشر مرات متتالية قط', en: 'I have never played a song ten times in a row' },
    { ar: 'لم أرسل رسالة ثم تمنيت لو لم أرسلها قط', en: 'I have never sent a message and wished I had not' },
    { ar: 'لم أفكر في تغيير مجال دراستي أو عملي قط', en: 'I have never considered changing my field of study or work' },
    { ar: 'لم أحلم حلماً استيقظت منه سعيداً جداً قط', en: 'I have never woken up extremely happy from a dream' },
    { ar: 'لم أسافر بلا خطة مسبقة قط', en: 'I have never traveled without any plan' },
    { ar: 'لم أضحك حتى أُتعب بطني قط', en: 'I have never laughed until my stomach hurt' },
    { ar: 'لم أتعلم من خطأ كبير قط', en: 'I have never learned from a big mistake' },
    { ar: 'لم أشاهد الغروب من مكان مرتفع قط', en: 'I have never watched a sunset from a high place' },
    { ar: 'لم أنسَ مفاتيحي داخل البيت قط', en: 'I have never locked myself out of my home' },
    { ar: 'لم أشعر بالحنين لمكان لم أعِش فيه قط', en: 'I have never felt nostalgic for a place I never lived in' }
];

module.exports = { TRUTHS, DARES, WOULD_YOU_RATHER, NEVER_HAVE_I_EVER };
